# Hosted Streamable-HTTP server image for mcp-for-ocp-graphql.
#
# Baked data approach: the baked RAG/schema data
# (mcp_for_ocp_graphql/data/{schema.json, milvus.db/}) is GENERATED BY CI ON THE
# RUNNER *before* `docker build`, then COPIED into the image via the project tree.
# We deliberately do NOT run schema_fetch / `uvx opencrane embed` inside the image:
# that would re-download the nomic embedding model on every build (slow, fragile).
# CI (.github/workflows/build-and-push.yml) bakes the data, then this Dockerfile
# copies the project (data/ included) and installs it.
FROM python:3.11-slim

# Pin uv via its official installer image (digest-pinned upstream) is overkill here;
# install a pinned uv version with pip instead so the toolchain is reproducible.
ENV UV_VERSION=0.8.19
RUN pip install --no-cache-dir "uv==${UV_VERSION}"

WORKDIR /app

# Copy the whole project, including the CI-baked mcp_for_ocp_graphql/data/.
COPY . .

# Install the project and its runtime deps (no dev group). Uses the committed
# uv.lock for a reproducible dependency set; --no-dev skips pytest etc.
RUN uv sync --no-dev --frozen

ENV PORT=3000
# PUBLIC_URL is read at runtime by app_http.build_http_app(); set it via the
# container platform (Scaleway) env. Defaults to http://localhost:$PORT if unset.
EXPOSE 3000

# Run the hosted HTTP entrypoint console script from the synced venv.
CMD ["uv", "run", "--no-dev", "--frozen", "mcp-for-ocp-graphql-http"]
