"""Tests for the Cherry Studio skill generator (scripts/build_cherry_skill.py).

The generator merges the plugin's agent (analyst framing + how-it-works) with the
querying skill (the full playbook) into a single Cherry-installable SKILL.md.
"""
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import build_cherry_skill as bcs  # noqa: E402

AGENT = (ROOT / "plugins/oc-platform-api/agents/opencollective-analyst.md").read_text()
SKILL = (ROOT / "plugins/oc-platform-api/skills/querying-opencollective-graphql/SKILL.md").read_text()


@pytest.fixture(scope="module")
def rendered() -> str:
    return bcs.render_cherry_skill(AGENT, SKILL)


def test_frontmatter_names_the_merged_skill(rendered):
    assert rendered.startswith("---\n")
    fm, _ = bcs._split(rendered)
    assert "name: opencollective-analyst" in fm
    assert "description:" in fm
    assert "Open Collective" in fm  # description carried from the agent


def test_marks_output_as_generated(rendered):
    assert "GENERATED by scripts/build_cherry_skill.py" in rendered
    assert "DO NOT EDIT" in rendered


def test_keeps_agent_analyst_behavior(rendered):
    assert "## How you work" in rendered
    assert "Restate the question" in rendered


def test_inlines_the_full_skill_playbook(rendered):
    # substance that lives only in the skill, not the agent's condensed rules
    assert "totalCount" in rendered
    assert "AccountWithHost" in rendered
    assert "inline fragment" in rendered
    assert "do not select these fields" in rendered.lower()  # PII rule from the skill


def test_drops_the_agents_pointer_and_condensed_rules(rendered):
    # the pointer only made sense when the skill was separate
    assert "see the bundled querying skill" not in rendered
    # the agent's condensed "Query rules" section is superseded by the full skill body
    assert "Query rules that save time" not in rendered
    # the agent's own tool list is dropped in favor of the skill's Overview
    assert "## The three tools" not in rendered


def test_errors_loudly_if_agent_structure_drifts():
    with pytest.raises(SystemExit):
        bcs.render_cherry_skill("---\nname: x\ndescription: y\n---\n\nNo how-you-work heading here.", SKILL)
