#!/usr/bin/env python3
"""Generate the Cherry Studio skill by merging the plugin's agent + querying skill.

Cherry Studio installs skills in Anthropic's Agent Skills format (a folder with a
SKILL.md). This repo's plugin ships that knowledge as two Claude-specific pieces:

  * the `opencollective-analyst` AGENT — analyst framing + how-it-works behavior, and
  * the `querying-opencollective-graphql` SKILL — the full query playbook.

Cherry has no subagent concept, so we fold both into one installable skill: the
agent's persona + "How you work" section, followed by the skill's full playbook
(which authoritatively covers the tools, gotchas, and PII rules — so the agent's
own condensed tool list and rules are dropped to avoid duplication).

The output (cherry-studio/opencollective-analyst/SKILL.md) is COMMITTED but
GENERATED — never hand-edit it. Edit the two sources and re-run this script:

    uv run python scripts/build_cherry_skill.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENT = ROOT / "plugins/oc-platform-api/agents/opencollective-analyst.md"
SKILL = ROOT / "plugins/oc-platform-api/skills/querying-opencollective-graphql/SKILL.md"
OUT = ROOT / "cherry-studio/opencollective-analyst/SKILL.md"

HEADER = (
    "<!-- GENERATED by scripts/build_cherry_skill.py from\n"
    "     plugins/oc-platform-api/agents/opencollective-analyst.md +\n"
    "     plugins/oc-platform-api/skills/querying-opencollective-graphql/SKILL.md.\n"
    "     DO NOT EDIT — edit those sources and re-run the script. -->"
)


def _split(text: str) -> tuple[str, str]:
    """Split a markdown file into (frontmatter-block, body). Frontmatter includes its
    delimiting `---` lines; body is everything after the closing `---`."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return "", text
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return "", text
    fm = "\n".join(lines[: end + 1])
    body = "\n".join(lines[end + 1 :]).lstrip("\n")
    return fm, body


def _field(frontmatter: str, key: str) -> str:
    for line in frontmatter.splitlines():
        if line.startswith(f"{key}:"):
            return line[len(key) + 1 :].strip()
    return ""


def _intro(body: str) -> str:
    """Text before the first `## ` heading."""
    out = []
    for line in body.splitlines():
        if line.startswith("## "):
            break
        out.append(line)
    return "\n".join(out).strip()


def _section(body: str, heading: str) -> str:
    """The `## heading` section (heading line included) up to the next `## ` or EOF."""
    lines = body.splitlines()
    start = next((i for i, ln in enumerate(lines) if ln.strip() == heading), None)
    if start is None:
        return ""
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
    return "\n".join(lines[start:end]).strip()


def render_cherry_skill(agent_text: str, skill_text: str) -> str:
    """Merge the agent (framing + How-you-work) and the skill (full playbook) into one
    SKILL.md. Raises SystemExit if the agent's expected structure is missing, so a
    source restructure fails loudly here (and in CI) instead of producing a silently
    wrong skill."""
    agent_fm, agent_body = _split(agent_text)
    _, skill_body = _split(skill_text)

    description = _field(agent_fm, "description")
    intro = _intro(agent_body)
    how = _section(agent_body, "## How you work")

    if not description:
        raise SystemExit("build_cherry_skill: agent frontmatter has no 'description' — update the script.")
    if not intro:
        raise SystemExit("build_cherry_skill: agent has no intro paragraph before the first '## ' — update the script.")
    if not how:
        raise SystemExit("build_cherry_skill: agent '## How you work' section not found — update the script.")
    if not skill_body.strip():
        raise SystemExit("build_cherry_skill: querying skill body is empty — update the script.")

    parts = [
        "---",
        "name: opencollective-analyst",
        f"description: {description}",
        "---",
        "",
        HEADER,
        "",
        intro,
        "",
        how,
        "",
        skill_body.strip(),
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    out = render_cherry_skill(AGENT.read_text(), SKILL.read_text())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(out)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(out)} bytes)")


if __name__ == "__main__":
    main()
